---
#       _                     _  __      _       __     ___            _        
#   ___| | __ _ _ __ ___   __| |/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
#  / __| |/ _` | '_ ` _ \ / _` | || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | (__| | (_| | | | | | | (_| | || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
#  \___|_|\__,_|_| |_| |_|\__,_| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#                               \_\_|        |___/_/                            
# boot-script
- name: boot-script | Clamd should be enabled
  when: clamd.enabled == true
  service:
    name:    "clamd"
    enabled: "yes"

- name: boot-script | Clamd should be started
  when: clamd.started == true
  service:
    name:  "clamd"
    state: "started"

