---
#       _                     _  __      _       __     ___            _        
#   ___| | __ _ _ __ ___   __| |/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
#  / __| |/ _` | '_ ` _ \ / _` | || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | (__| | (_| | | | | | | (_| | || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
#  \___|_|\__,_|_| |_| |_|\__,_| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#                               \_\_|        |___/_/                            
# make-config
- block:
    - name: make-config | RedHat | Log directory should be created
      file:
        path:  "{{ clamd.loggingdir }}"
        mode:  "0775"
        owner: "root"
        group: "virusgroup"
        state: "directory"

    - name: make-config | RedHat | freshclam.conf should be deployed
      template:
        src:   "etc/freshclam.conf.j2"
        dest:  "/etc/freshclam.conf"
        mode:  "0644"
        owner: "root"
        group: "root"

    - name: make-config | RedHat | clamd.conf should be deployed
      notify: Restart clamd
      template:
        src:   "etc/clamd.conf.j2"
        dest:  "/etc/clamd.conf"
        mode:  "0644"
        owner: "root"
        group: "root"

    - name: make-config | RedHat | Log Rotation should be configured
      template:
        src:   "etc/logrotate.d/clamav-update.j2"
        dest:  "/etc/logrotate.d/clamav-update.j2"
        mode:  "0644"
        owner: "root"
        group: "root"

    - name: make-config | RedHat | crontab should be deployed
      template:
        src:   "etc/cron.d/clamav-update.j2"
        dest:  "/etc/cron.d/clamav-update.j2"
        mode:  "0644"
        owner: "root"
        group: "root"

    - name: make-config | RedHat | /etc/sysconfig/freshcram should be deployed
      template:
        src:   "etc/sysconfig/freshclam.j2"
        dest:  "/etc/sysconfig/freshclam"
        mode:  "0644"
        owner: "root"
        group: "root"
  when: ansible_os_family == "RedHat"

