---
#       _                     _  __      _       __     ___                     _ _               
#   ___| | __ _ _ __ ___   __| |/ /_ __ | | ____ \ \   / / |__   __ _ _ __   __| | | ___ _ __ ___ 
#  / __| |/ _` | '_ ` _ \ / _` | || '_ \| |/ / _` | | / /| '_ \ / _` | '_ \ / _` | |/ _ \ '__/ __|
# | (__| | (_| | | | | | | (_| | || |_) |   < (_| | |/ / | | | | (_| | | | | (_| | |  __/ |  \__ \
#  \___|_|\__,_|_| |_| |_|\__,_| || .__/|_|\_\__, | /_/  |_| |_|\__,_|_| |_|\__,_|_|\___|_|  |___/
#                               \_\_|        |___/_/                                              
# handlers file for ar-clamd-pkg
- name: Restart clamd
  service:
    name:  "clamd"
    state: "restarted"

